### ISSUE TITLE
please submit Swift  podspec to cocoapods 

### ISSUE THREAD

**Issue by yushuyi** [bennyguitar/Colours#26]
thanks

**Comment by bennyguitar** [comment]
Seems like it's still prerelease and they don't have good, concise documentation on making a swift podspec yet. Do you have any info on that? I'd love to submit it, but I don't wanna' mess anything up for current users.

**Comment by allaire** [comment]
I'm using the prerelease and it works well! Alamofire is now submitted officially, I think this would be a good time to do it :)

**Comment by bennyguitar** [comment]
It's been submitted. You can use 5.6.0 or above for Swift, just use `pod 'Colours/Swift'` for the swift subsepc. I haven't tried this, so if it doesn't work please comment here.

**Comment by bennyguitar** [comment]
According to #28 this didn't work as intended. Swift has been removed as a subspec.
