### ISSUE TITLE
Odd behavior with darken/lighten

### ISSUE THREAD

**Issue by jimbojsb** [bennyguitar/Colours#27]
Hi,

I think there is either a bug with darken or I'm misunderstanding how to use it. Given an existing UIColor, if I lighten it by 0.15f, it lightens correctly (albeit slightly more than I might expect, but other color libraries, such as the one in less.js, behave identically). However, darkening by any amount results in a color that is not exactly black, but essentially black. What's odd is that lightening by a negative float gives exactly the results I'd expect.

```objc
searchInput.backgroundColor = [[Colors teal] lighten:-0.15f]; // perfect
searchInput.backgroundColor = [[Colors teal] darken:0.15f]; // black

```

![screen shot 2015-01-15 at 5 48 07 pm](https://cloud.githubusercontent.com/assets/107836/5769271/bea6ec2e-9cde-11e4-804f-0f43ebd7694b.png)
![screen shot 2015-01-15 at 5 48 26 pm](https://cloud.githubusercontent.com/assets/107836/5769272/becfade4-9cde-11e4-89d7-38e2b45987c0.png)

**Comment by bennyguitar** [comment]
The way it works, is it takes the float you pass in and multiplies the brightness of the color (from the Hue, Saturation, Brightness color formulation) by that value. So a .15 will result in a color that is 15% as bright as it used to be.

This might be confusing, and I'll look at making it what seems the most common-sense way of doing it.

**Comment by jimbojsb** [comment]
Ah, I see. Darken by .85f gives me the result I was looking for. I think maybe just the method names are slightly confusing or even just updating the readme with with what you noted above is sufficient.

**Comment by allaire** [comment]
This is really confusing. I suggest we take inspiration from sass (http://sass-lang.com/documentation/Sass/Script/Functions.html#darken-instance_method)

darken(#ccc, 5%) makes #ccc 5% darker

**Comment by bennyguitar** [comment]
Ok, it makes sense now. If you do `[[UIColor plumColor] darken:0.05]` it makes a 5% darker color.

**Comment by allaire** [comment]
Works flawlessly @bennyguitar  (currently using :head)
