### ISSUE TITLE
Error:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `X' in: -Xlinker

### ISSUE THREAD

**Issue by sexytaeho** [bennyguitar/Colours#28]
in your updates(5.6.0) are experiencing problems similar to the following (still xcode6.1.1): 

http://stackoverflow.com/questions/24041962/static-linking-with-swift-xcode6-beta

the official reason is that looks like this : "Xcode does not support building static libraries that include Swift code."

**Comment by bennyguitar** [comment]
This is fixed now. It looks like the podspec was including the subspec for swift in the main thing. Removed swift for now.

**Comment by sexytaeho** [comment]
huge thx!!
