### ISSUE TITLE
Convert from hex string!

### ISSUE THREAD

**Issue by EMidee66** [bennyguitar/Colours#30]
One of these has an issue: 

- func hexString() -> String
- init(hex: String)

because I get different colors.

ex. Color(hex: Color.successColor().hexString()) -> returns blue

**Comment by bennyguitar** [comment]
It looks like the init method is borked somehow. Good find and I'll try and fix it this weekend.

**Comment by EMidee66** [comment]
I wonder why they call them bugs? :P

    convenience init(hex: String) {
        var rgbInt: UInt64 = 0
        let newHex: NSString = NSString(string: hex).stringByReplacingOccurrencesOfString("#", withString: "")
        var scanner = NSScanner(string: newHex)
        scanner.scanHexLongLong(&rgbInt)
        let r: CGFloat = CGFloat((rgbInt & 0xFF0000) >> 16)/255.0
        let g: CGFloat = CGFloat((rgbInt & 0x00FF00) >> 8)/255.0
        let b: CGFloat = CGFloat(rgbInt & 0x0000FF)/255.0
        self.init(red: r, green: g, blue: b, alpha: 1.0)
    }
