### ISSUE TITLE
CIELAB transform block in swift takes too long to be solved

### ISSUE THREAD

**Issue by nheagy** [bennyguitar/Colours#31]
Seeing this in Xcode 6.3/Swift 1.2:

https://www.dropbox.com/s/z7t23oxtg9bsgli/Screenshot%202015-03-11%2022.59.23.png?dl=0

**Comment by bennyguitar** [comment]
I'll break it up into smaller chunks. Really hate that Swift can't handle that when Objective-C can -_-

**Comment by bennyguitar** [comment]
I'll reopen this issue when Xcode 6.3 becomes public. Right now, I'm not worried about beta builds. Xcode 6.2 handles it perfectly fine.
