### ISSUE TITLE
Semantic issue on function fabsf warning in Xcode 6.3

### ISSUE THREAD

**Issue by gzfrancisco** [bennyguitar/Colours#33]
I just update to Xcode 6.3 and the compiler sends me 2 warnings:

> Project/Pods/Colours/Colours.m:663:9: Absolute value function 'fabsf' given an argument of type 'double' but has parameter of type 'float' which may cause truncation of value

> Project/Pods/Colours/Colours.m:670:27: Absolute value function 'fabsf' given an argument of type 'double' but has parameter of type 'float' which may cause truncation of value

I can make the change, but I'm not sure if its a great idea. If you need help, I can make the pull request.

**Comment by bennyguitar** [comment]
Yeah you should open a pull request to fix. I don't have a ton of time to update this repo over the next couple days. If you submit a pull request, also bump up the podspec version to `x.x.(x + 1)` and I'll tag and push a new spec up to Cocoapods.
