### ISSUE TITLE
RGBA <-> HSBA color conversion issue

### ISSUE THREAD

**Issue by winstonyang** [bennyguitar/Colours#39]
Hello,

I was trying to debug the darken/lighten functions while it used to work properly, it does not seem to any more.  I've looked into this some more and found if you try to convert colors between 2 color spaces, they are not equivalent.  For instance, try this:

NSArray *hsbColorArray = [[UIColor blueColor] hsbaArray];   ===> Yields a blue color
UIColor *color = [UIColor colorFromHSBAArray:hsbColorArray];  ===> Yields a red color

Thanks.

**Comment by winstonyang** [comment]
Apologies.  Issue was due to another podfile overriding colorWithHue function.  This works properly.

**Comment by bennyguitar** [comment]
No worries man, I was about to test this out, but I could have sworn my unit tests would have caught this. Thanks for using this library.

**Comment by winstonyang** [comment]
I'm the one who should thank you for this great library and it is very well written.  Appreciate it!
