### ISSUE TITLE
all Colors

### ISSUE THREAD

**Issue by qxw** [bennyguitar/Colours#44]
I intercepted one contains all the colors of the picture, to facilitate viewing use .
![allcolors](https://cloud.githubusercontent.com/assets/10415105/9779864/6b11cd14-57b3-11e5-8809-1b2a381c367d.jpg)

**Comment by bennyguitar** [comment]
I'm not sure what this is intended to be for? I'm keen on keeping the table on the readme because it puts 3 colors per line, so less scrolling overall to get to the following information.
