### ISSUE TITLE
Swift 3 branch

### ISSUE THREAD

**Issue by lfarah** [bennyguitar/Colours#52]
Hey @bennyguitar, I'd be cool to update **Colours** to Swift 3 since `UIColor.blueColor()`, for example, is now `UIColor.blue()`

**Comment by grhowes** [comment]
I'd second this request.

**Comment by lfarah** [comment]
We can just create a ```swift3``` branch for now

**Comment by bennyguitar** [comment]
I believe this has been done, but it may need refactoring for the other color definitions.
